apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lightnyai-beta-origin
  namespace: gpt
spec:
  ingressClassName: public-awg
  rules:
    - host: lightnyai-beta.internal
      http:
        paths:
          - path: /health/live
            pathType: Exact
            backend:
              service:
                name: tg-mini-beta-backend
                port:
                  number: 80
          - path: /health/ready
            pathType: Exact
            backend:
              service:
                name: tg-mini-beta-backend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tg-mini-beta-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tg-mini-beta-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - lightnyai-beta.internal
      secretName: lightnyai-beta-origin-tls
