apiVersion: v1
kind: ConfigMap
metadata:
  name: tg-bot-images-tcp-proxy
  namespace: gpt
data:
  nginx.conf: |
    events {}
    stream {
        resolver 1.1.1.1 8.8.8.8 valid=30s;
        server {
            listen 10.77.0.1:8443;
            proxy_pass tg-bot-images.lightny.pro:443;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-bot-images-tcp-proxy-node2
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-bot-images-tcp-proxy
  template:
    metadata:
      labels:
        app: tg-bot-images-tcp-proxy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: k8s-node-2
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: tls-pass
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: tg-bot-images-tcp-proxy
