apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtrack-pvc-longhorn
  namespace: gamedev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-r2
  resources:
    requests:
      storage: 20Gi
