apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-awg
  namespace: ingress
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: nginx-ingress-awg
    app.kubernetes.io/component: controller
  ports:
  - name: https-awg
    protocol: TCP
    port: 443
    targetPort: https
    nodePort: 30445
