apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-awg-conf
  namespace: ingress
data:
  use-forwarded-headers: "true"
  enable-real-ip: "true"
  proxy-real-ip-cidr: 10.77.0.2/32
  compute-full-forwarded-for: "true"
