"""Added translations for name and description of tiers

Revision ID: 037fa8172779
Revises: 116551e36f19
Create Date: 2025-11-27 12:51:01.873972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '037fa8172779'
down_revision: Union[str, Sequence[str], None] = '116551e36f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tier', sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subscription_tier', sa.Column('description_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint(None, 'subscription_tier', ['name_ru'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_tier', type_='unique')
    op.drop_column('subscription_tier', 'description_ru')
    op.drop_column('subscription_tier', 'name_ru')
    # ### end Alembic commands ###
