"""Added index and public bool to the subscription_tier

Revision ID: 116551e36f19
Revises: 99fe5fbbbad2
Create Date: 2025-11-27 11:35:50.984821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '116551e36f19'
down_revision: Union[str, Sequence[str], None] = '99fe5fbbbad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tier', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('subscription_tier', sa.Column('index', sa.Integer(), nullable=True))

    op.execute("""
               UPDATE subscription_tier
               SET is_public = True
               WHERE is_public IS NULL
               """)

    op.execute("""
               UPDATE subscription_tier
               SET index = 1
               WHERE index IS NULL
               """)

    op.alter_column(
        'subscription_tier',
        'is_public',
        existing_type=sa.Boolean(),
        nullable=False,
    )

    op.alter_column(
        'subscription_tier',
        'index',
        existing_type=sa.Integer(),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_tier', 'index')
    op.drop_column('subscription_tier', 'is_public')
    # ### end Alembic commands ###
