"""adding image quality

Revision ID: 1558e84cc1e1
Revises: 94b953a754ae
Create Date: 2026-01-26 14:26:10.071982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1558e84cc1e1'
down_revision: Union[str, Sequence[str], None] = '94b953a754ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'image_quality_pricing',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('image_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('quality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('credit_cost', sa.Float(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_image_quality_pricing_image_model'),
        'image_quality_pricing',
        ['image_model'],
        unique=False
    )

    # 1) Add as nullable first (safe for existing rows)
    op.add_column(
        'conversation',
        sa.Column('image_quality', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )

    # 2) Backfill existing rows
    op.execute("UPDATE conversation SET image_quality = 'low' WHERE image_quality IS NULL")

    # 3) Enforce NOT NULL going forward
    op.alter_column(
        'conversation',
        'image_quality',
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'image_quality')
    op.drop_index(op.f('ix_image_quality_pricing_image_model'), table_name='image_quality_pricing')
    op.drop_table('image_quality_pricing')
    # ### end Alembic commands ###