"""adding image quality

Revision ID: 1558e84cc1e1
Revises: 94b953a754ae
Create Date: 2026-01-26 14:26:10.071982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1558e84cc1e1'
down_revision: Union[str, Sequence[str], None] = '94b953a754ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('image_quality_pricing'):
        op.create_table(
            'image_quality_pricing',
            sa.Column('id', sa.Uuid(), nullable=False),
            sa.Column('image_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('quality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('credit_cost', sa.Float(), nullable=False),
            sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )

    pricing_indexes = {idx["name"] for idx in inspector.get_indexes('image_quality_pricing')}
    pricing_index_name = op.f('ix_image_quality_pricing_image_model')
    if pricing_index_name not in pricing_indexes:
        op.create_index(
            pricing_index_name,
            'image_quality_pricing',
            ['image_model'],
            unique=False
        )

    conversation_columns = {col["name"] for col in inspector.get_columns('conversation')}
    if 'image_quality' not in conversation_columns:
        op.add_column(
            'conversation',
            sa.Column('image_quality', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    op.execute("UPDATE conversation SET image_quality = 'low' WHERE image_quality IS NULL")

    op.alter_column(
        'conversation',
        'image_quality',
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'image_quality')
    op.drop_index(op.f('ix_image_quality_pricing_image_model'), table_name='image_quality_pricing')
    op.drop_table('image_quality_pricing')
    # ### end Alembic commands ###
