"""added ledger and subscription tier

Revision ID: 187a8294f1c2
Revises: 691195fb5ac4
Create Date: 2025-11-07 17:15:23.193667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '187a8294f1c2'
down_revision: Union[str, Sequence[str], None] = '691195fb5ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_tier',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('monthly_images', sa.Integer(), nullable=False),
    sa.Column('monthly_docs', sa.Integer(), nullable=False),
    sa.Column('monthly_deepsearch', sa.Integer(), nullable=False),
    sa.Column('allowed_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_tier_name'), 'subscription_tier', ['name'], unique=True)
    op.create_table('access_code',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('discount_months', sa.Integer(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_code_code'), 'access_code', ['code'], unique=True)
    op.create_index(op.f('ix_access_code_expires_at'), 'access_code', ['expires_at'], unique=False)
    op.create_table('request_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('assistant_message_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sa.Enum('reserved', 'consumed', 'refunded', 'failed', name='state'), nullable=False),
    sa.Column('tool_choice', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("feature IN ('text','image','doc','deepsearch','web_search')", name='ck_request_feature'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'request_id', name='uq_user_reqid')
    )
    op.create_index(op.f('ix_request_ledger_assistant_message_id'), 'request_ledger', ['assistant_message_id'], unique=False)
    op.create_index(op.f('ix_request_ledger_conversation_id'), 'request_ledger', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_request_ledger_created_at'), 'request_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_ledger_feature'), 'request_ledger', ['feature'], unique=False)
    op.create_index(op.f('ix_request_ledger_model_name'), 'request_ledger', ['model_name'], unique=False)
    op.create_index(op.f('ix_request_ledger_request_id'), 'request_ledger', ['request_id'], unique=False)
    op.create_index(op.f('ix_request_ledger_state'), 'request_ledger', ['state'], unique=False)
    op.create_index(op.f('ix_request_ledger_user_id'), 'request_ledger', ['user_id'], unique=False)
    op.create_table('tier_model_limit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_requests', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_id', 'model_name', name='uq_tier_model')
    )
    op.create_index(op.f('ix_tier_model_limit_model_name'), 'tier_model_limit', ['model_name'], unique=False)
    op.create_index(op.f('ix_tier_model_limit_tier_id'), 'tier_model_limit', ['tier_id'], unique=False)
    op.create_table('user_subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', name='subscriptionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('discount_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscription_discount_expires_at'), 'user_subscription', ['discount_expires_at'], unique=False)
    op.create_index(op.f('ix_user_subscription_expires_at'), 'user_subscription', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_subscription_started_at'), 'user_subscription', ['started_at'], unique=False)
    op.create_index(op.f('ix_user_subscription_tier_id'), 'user_subscription', ['tier_id'], unique=False)
    op.create_index(op.f('ix_user_subscription_user_id'), 'user_subscription', ['user_id'], unique=False)
    op.create_table('referral',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inviter_user_id', sa.Uuid(), nullable=False),
    sa.Column('invitee_user_id', sa.Uuid(), nullable=False),
    sa.Column('access_code_id', sa.Uuid(), nullable=True),
    sa.Column('reward_applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_code.id'], ),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_user_id', name='uq_referral_unique_invitee')
    )
    op.create_index(op.f('ix_referral_invitee_user_id'), 'referral', ['invitee_user_id'], unique=False)
    op.create_index(op.f('ix_referral_inviter_user_id'), 'referral', ['inviter_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_inviter_user_id'), table_name='referral')
    op.drop_index(op.f('ix_referral_invitee_user_id'), table_name='referral')
    op.drop_table('referral')
    op.drop_index(op.f('ix_user_subscription_user_id'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_tier_id'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_started_at'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_expires_at'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_discount_expires_at'), table_name='user_subscription')
    op.drop_table('user_subscription')
    op.drop_index(op.f('ix_tier_model_limit_tier_id'), table_name='tier_model_limit')
    op.drop_index(op.f('ix_tier_model_limit_model_name'), table_name='tier_model_limit')
    op.drop_table('tier_model_limit')
    op.drop_index(op.f('ix_request_ledger_user_id'), table_name='request_ledger')
    op.drop_index(op.f('ix_request_ledger_state'), table_name='request_ledger')
    op.drop_index(op.f('ix_request_ledger_request_id'), table_name='request_ledger')
    op.drop_index(op.f('ix_request_ledger_model_name'), table_name='request_ledger')
    op.drop_index(op.f('ix_request_ledger_feature'), table_name='request_ledger')
    op.drop_index(op.f('ix_request_ledger_created_at'), table_name='request_ledger')
    op.drop_index(op.f('ix_request_ledger_conversation_id'), table_name='request_ledger')
    op.drop_index(op.f('ix_request_ledger_assistant_message_id'), table_name='request_ledger')
    op.drop_table('request_ledger')
    op.drop_index(op.f('ix_access_code_expires_at'), table_name='access_code')
    op.drop_index(op.f('ix_access_code_code'), table_name='access_code')
    op.drop_table('access_code')
    op.drop_index(op.f('ix_subscription_tier_name'), table_name='subscription_tier')
    op.drop_table('subscription_tier')
    # ### end Alembic commands ###
