"""empty message

Revision ID: 2f029eb8dad7
Revises: 
Create Date: 2025-10-27 16:37:15.523600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f029eb8dad7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aimodelpricing',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit_price_input_per_1m', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price_output_per_1m', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price_reasoning_per_1m', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price_web_search_call', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price_image_generation', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aimodelpricing_model_name'), 'aimodelpricing', ['model_name'], unique=False)
    op.create_index(op.f('ix_aimodelpricing_provider'), 'aimodelpricing', ['provider'], unique=False)
    op.create_index('ix_pricing_provider_model_active', 'aimodelpricing', ['provider', 'model_name', 'is_active'], unique=False)
    op.create_table('tokenusage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('web_search_calls', sa.Integer(), nullable=False),
    sa.Column('images_generated', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost_input', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_output', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_reasoning', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_web_search', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('cost_images', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_usage_user_created', 'tokenusage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tokenusage_created_at'), 'tokenusage', ['created_at'], unique=False)
    op.create_index(op.f('ix_tokenusage_model_name'), 'tokenusage', ['model_name'], unique=False)
    op.create_index(op.f('ix_tokenusage_provider'), 'tokenusage', ['provider'], unique=False)
    op.create_index(op.f('ix_tokenusage_request_id'), 'tokenusage', ['request_id'], unique=False)
    op.alter_column('conversation', 'model',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'gpt-5-nano'::text"))
    op.alter_column('conversation', 'system_prompt',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation', 'system_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('conversation', 'model',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'gpt-5-nano'::text"))
    op.drop_index(op.f('ix_tokenusage_request_id'), table_name='tokenusage')
    op.drop_index(op.f('ix_tokenusage_provider'), table_name='tokenusage')
    op.drop_index(op.f('ix_tokenusage_model_name'), table_name='tokenusage')
    op.drop_index(op.f('ix_tokenusage_created_at'), table_name='tokenusage')
    op.drop_index('ix_token_usage_user_created', table_name='tokenusage')
    op.drop_table('tokenusage')
    op.drop_index('ix_pricing_provider_model_active', table_name='aimodelpricing')
    op.drop_index(op.f('ix_aimodelpricing_provider'), table_name='aimodelpricing')
    op.drop_index(op.f('ix_aimodelpricing_model_name'), table_name='aimodelpricing')
    op.drop_table('aimodelpricing')
    # ### end Alembic commands ###
