"""Addding recurring field for subscription tiers

Revision ID: 50a6ef54df6c
Revises: e92204ee20d7
Create Date: 2025-12-10 13:32:35.184149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50a6ef54df6c'
down_revision: Union[str, Sequence[str], None] = 'e92204ee20d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tier', sa.Column('is_recurring', sa.Boolean(), nullable=True))

    op.execute("""
               UPDATE subscription_tier
               SET is_recurring = TRUE
               WHERE is_recurring IS NULL
               """)

    # 3) Make the column NOT NULL
    op.alter_column(
        'subscription_tier',
        'is_recurring',
        existing_type=sa.Boolean(),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_tier', 'is_recurring')
    # ### end Alembic commands ###
