"""Added expires at to the tier granted with the code

Revision ID: 560efe9638b6
Revises: cafc682061fc
Create Date: 2025-11-22 16:05:17.811333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '560efe9638b6'
down_revision: Union[str, Sequence[str], None] = 'cafc682061fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'access_code',
        sa.Column('tier_expires_in_days', sa.Integer(), nullable=True)
    )

    # 2) Backfill existing rows
    # adjust this to your real logic
    op.execute("""
               UPDATE access_code
               SET tier_expires_in_days = 30
               WHERE tier_expires_in_days IS NULL
               """)

    # 3) Make the column NOT NULL
    op.alter_column(
        'access_code',
        'tier_expires_in_days',
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_code', 'tier_expires_in_days')
    # ### end Alembic commands ###
