"""Refactor for the new pricing model

Revision ID: 5c907abb7f5e
Revises: 74b7a1f39ae2
Create Date: 2026-01-12 10:04:15.201100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c907abb7f5e'
down_revision: Union[str, Sequence[str], None] = '74b7a1f39ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_ledger', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('subscription_tier', sa.Column('daily_image_limit', sa.Integer(), nullable=True))


    op.execute("""
               UPDATE request_ledger
               SET cost = 1
               WHERE cost IS NULL
               """)

    # 3) Make the column NOT NULL
    op.alter_column(
        'request_ledger',
        'cost',
        existing_type=sa.Integer(),
        nullable=False,
    )

    op.execute("""
               UPDATE subscription_tier
               SET daily_image_limit = 10
               WHERE daily_image_limit IS NULL
               """)

    # 3) Make the column NOT NULL
    op.alter_column(
        'subscription_tier',
        'daily_image_limit',
        existing_type=sa.Integer(),
        nullable=False,
    )

    op.drop_column('subscription_tier', 'monthly_images')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tier', sa.Column('monthly_images', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('subscription_tier', 'daily_image_limit')
    op.drop_column('request_ledger', 'cost')
    # ### end Alembic commands ###
