"""allowed usage and subscription tiers added

Revision ID: 691195fb5ac4
Revises: ecbe436f5c94
Create Date: 2025-11-07 10:50:02.298017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '691195fb5ac4'
down_revision: Union[str, Sequence[str], None] = 'ecbe436f5c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
