"""new migration

Revision ID: 69a355643294
Revises: f3a1b2c4d5e7
Create Date: 2026-02-07 15:41:22.320263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69a355643294'
down_revision: Union[str, Sequence[str], None] = 'f3a1b2c4d5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_pack_name_ru'), table_name='usage_pack')
    op.create_unique_constraint(None, 'usage_pack', ['name_ru'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_pack', type_='unique')
    op.create_index(op.f('ix_usage_pack_name_ru'), 'usage_pack', ['name_ru'], unique=True)
    # ### end Alembic commands ###
