"""Addding image_model to conversation#

Revision ID: 74b7a1f39ae2
Revises: df5399a40bb0
Create Date: 2026-01-06 18:17:35.807873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74b7a1f39ae2'
down_revision: Union[str, Sequence[str], None] = 'df5399a40bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('image_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'image_model')
    # ### end Alembic commands ###
