"""Adding Payment Method for reccurent payments

Revision ID: 74eb42b3a343
Revises: 0e11c6601e74
Create Date: 2025-12-07 13:45:10.904533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74eb42b3a343'
down_revision: Union[str, Sequence[str], None] = '0e11c6601e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_payment_method_rebill_id'), table_name='payment_method')
    # op.drop_index(op.f('ix_payment_method_user_id'), table_name='payment_method')
    op.drop_table('payment_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rebill_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('card_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pan', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('exp_date', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('payment_method_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_method_pkey'))
    )
    op.create_index(op.f('ix_payment_method_user_id'), 'payment_method', ['user_id'], unique=False)
    op.create_index(op.f('ix_payment_method_rebill_id'), 'payment_method', ['rebill_id'], unique=False)
    # ### end Alembic commands ###
