"""Addding has_sent_first_message for the user metrics

Revision ID: 7648cf228c4b
Revises: 50a6ef54df6c
Create Date: 2025-12-22 16:23:31.020260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7648cf228c4b'
down_revision: Union[str, Sequence[str], None] = '50a6ef54df6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('has_sent_first_message', sa.Boolean(), nullable=True))

    op.execute("""
               UPDATE app_user
               SET has_sent_first_message = False
               WHERE has_sent_first_message IS NULL
               """)

    op.alter_column(
        'app_user',
        'has_sent_first_message',
        existing_type=sa.Boolean(),
        nullable=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'has_sent_first_message')
    # ### end Alembic commands ###
