"""add timestamps to conversation and message

Revision ID: 78926143861c
Revises: 037fa8172779
Create Date: 2025-12-08 10:37:27.389712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78926143861c'
down_revision: Union[str, Sequence[str], None] = '037fa8172779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversation_updated_at'), 'conversation', ['updated_at'], unique=False)
    op.add_column('message', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_column('message', 'created_at')
    op.drop_index(op.f('ix_conversation_updated_at'), table_name='conversation')
    op.drop_column('conversation', 'updated_at')
    # ### end Alembic commands ###
