"""removing conversation id from usage when it is deleted

Revision ID: 7e65b32f74f8
Revises: 2f029eb8dad7
Create Date: 2025-10-29 17:09:31.712719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e65b32f74f8'
down_revision: Union[str, Sequence[str], None] = '2f029eb8dad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tokenusage_conversation_id_fkey'), 'tokenusage', type_='foreignkey')
    op.create_foreign_key(None, 'tokenusage', 'conversation', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokenusage', type_='foreignkey')
    op.create_foreign_key(op.f('tokenusage_conversation_id_fkey'), 'tokenusage', 'conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
