"""adding fields to message_content

Revision ID: 8f7fc27edd2a
Revises: 7e65b32f74f8
Create Date: 2025-10-29 18:04:39.210257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f7fc27edd2a'
down_revision: Union[str, Sequence[str], None] = '7e65b32f74f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messagecontent', sa.Column('ordinal', sa.Integer()))
    op.add_column('messagecontent', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messagecontent', 'data')
    op.drop_column('messagecontent', 'ordinal')
    # ### end Alembic commands ###
