"""Refactor for the new pricing model Fix

Revision ID: 94b953a754ae
Revises: 5c907abb7f5e
Create Date: 2026-01-12 14:17:55.469662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94b953a754ae'
down_revision: Union[str, Sequence[str], None] = '5c907abb7f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_tier', 'monthly_images',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_tier', 'monthly_images',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
