"""Removed unused fields in the user subscription table

Revision ID: 99fe5fbbbad2
Revises: 560efe9638b6
Create Date: 2025-11-22 16:17:25.382381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99fe5fbbbad2'
down_revision: Union[str, Sequence[str], None] = '560efe9638b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_subscription_discount_expires_at'), table_name='user_subscription')
    op.drop_column('user_subscription', 'discount_percent')
    op.drop_column('user_subscription', 'discount_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('discount_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_subscription', sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_user_subscription_discount_expires_at'), 'user_subscription', ['discount_expires_at'], unique=False)
    # ### end Alembic commands ###
