"""Added more robust access code management

Revision ID: cafc682061fc
Revises: 187a8294f1c2
Create Date: 2025-11-22 12:47:51.198060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cafc682061fc'
down_revision: Union[str, Sequence[str], None] = '187a8294f1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_code_discounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('access_code_id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_code.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usertierdiscount',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tier_id', sa.Uuid(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('access_code_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_code.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usertierdiscount_user_id'), 'usertierdiscount', ['user_id'], unique=False)
    op.create_index(op.f('ix_usertierdiscount_valid_until'), 'usertierdiscount', ['valid_until'], unique=False)
    op.alter_column('access_code', 'tier_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('access_code', 'discount_months')
    op.drop_column('access_code', 'discount_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_code', sa.Column('discount_percent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('access_code', sa.Column('discount_months', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('access_code', 'tier_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_usertierdiscount_valid_until'), table_name='usertierdiscount')
    op.drop_index(op.f('ix_usertierdiscount_user_id'), table_name='usertierdiscount')
    op.drop_table('usertierdiscount')
    op.drop_table('access_code_discounts')
    # ### end Alembic commands ###
