"""Addding campaign for the user

Revision ID: df5399a40bb0
Revises: 7648cf228c4b
Create Date: 2025-12-22 18:35:21.246856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df5399a40bb0'
down_revision: Union[str, Sequence[str], None] = '7648cf228c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('campaign', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_app_user_campaign'), 'app_user', ['campaign'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_user_campaign'), table_name='app_user')
    op.drop_column('app_user', 'campaign')
    # ### end Alembic commands ###
