"""add payment tables 2

Revision ID: e92204ee20d7
Revises: 78926143861c
Create Date: 2025-12-08 15:30:31.538114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e92204ee20d7'
down_revision: Union[str, Sequence[str], None] = '78926143861c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tbank_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tbank_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_tbank_payment_id'), 'payment', ['tbank_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_tier_name'), 'payment', ['tier_name'], unique=False)
    op.create_index(op.f('ix_payment_user_id'), 'payment', ['user_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rebill_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('card_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exp_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_rebill_id'), 'payment_methods', ['rebill_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_rebill_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_payment_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_tier_name'), table_name='payment')
    op.drop_index(op.f('ix_payment_tbank_payment_id'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
