"""Adding derived_image

Revision ID: ecbe436f5c94
Revises: 8f7fc27edd2a
Create Date: 2025-11-06 11:31:38.524829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecbe436f5c94'
down_revision: Union[str, Sequence[str], None] = '8f7fc27edd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derived_image',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_side', sa.Integer(), nullable=False),
    sa.Column('derived_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_key', 'target_format', 'max_side', name='uq_derived_image_variant')
    )
    op.create_index(op.f('ix_derived_image_created_at'), 'derived_image', ['created_at'], unique=False)
    op.create_index(op.f('ix_derived_image_derived_key'), 'derived_image', ['derived_key'], unique=True)
    op.create_index(op.f('ix_derived_image_original_key'), 'derived_image', ['original_key'], unique=False)
    op.create_index(op.f('ix_derived_image_target_format'), 'derived_image', ['target_format'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_derived_image_target_format'), table_name='derived_image')
    op.drop_index(op.f('ix_derived_image_original_key'), table_name='derived_image')
    op.drop_index(op.f('ix_derived_image_derived_key'), table_name='derived_image')
    op.drop_index(op.f('ix_derived_image_created_at'), table_name='derived_image')
    op.drop_table('derived_image')
    # ### end Alembic commands ###
