import os


class Settings:
    R2_BUCKET = os.environ["R2_BUCKET"]
    R2_ENDPOINT = os.environ["R2_ENDPOINT"]
    R2_REGION = os.getenv("R2_REGION", "auto")
    R2_ACCESS_KEY_ID = os.environ["R2_ACCESS_KEY_ID"]
    R2_SECRET_ACCESS_KEY = os.environ["R2_SECRET_ACCESS_KEY"]
    AUDIO_TRANSCRIPTION_R2_BUCKET = os.getenv("AUDIO_TRANSCRIPTION_R2_BUCKET", "").strip()
    AUDIO_TRANSCRIPTION_R2_ENDPOINT = os.getenv("AUDIO_TRANSCRIPTION_R2_ENDPOINT", "").strip()
    AUDIO_TRANSCRIPTION_R2_REGION = os.getenv("AUDIO_TRANSCRIPTION_R2_REGION", "auto").strip()
    AUDIO_TRANSCRIPTION_R2_ACCESS_KEY_ID = os.getenv("AUDIO_TRANSCRIPTION_R2_ACCESS_KEY_ID", "").strip()
    AUDIO_TRANSCRIPTION_R2_SECRET_ACCESS_KEY = os.getenv("AUDIO_TRANSCRIPTION_R2_SECRET_ACCESS_KEY", "").strip()
    AUDIO_TRANSCRIPTION_R2_SESSION_TOKEN = os.getenv("AUDIO_TRANSCRIPTION_R2_SESSION_TOKEN", "").strip()
    AUDIO_TRANSCRIPTION_R2_CREDENTIAL_EXPIRES_AT = os.getenv("AUDIO_TRANSCRIPTION_R2_CREDENTIAL_EXPIRES_AT", "").strip()
    R2_PUBLIC_BASE_URL = os.getenv("R2_PUBLIC_BASE_URL")  # optional
    R2_OPENAI_PUBLIC_BASE_URL = os.getenv("R2_OPENAI_PUBLIC_BASE_URL") or R2_PUBLIC_BASE_URL


